### ISSUE TITLE
Inicio de sesión y añadir vehículos

### ISSUE THREAD

**Issue by Javitoox** [ISPP-AparkApp/aparkapp-frontend#4]
Se deberá implementar la posibilidad a los usuarios de iniciar de sesión y también el registrar vehículos asociados a su cuenta:

- [ ] FRQ-11: El sistema deberá posibilitar el registro de vehículos asociados a un perfil.
- [ ] CRQ-01: Un vehículo no puede ser registrado más de una vez por la misma cuenta, sí por otras
- [ ] CRQ-06: Un usuario puede registrar varios vehículos asociados a su perfil.

**Comment by maribelrb22** [comment]
CRQ-01, CRQ-06 corresponde a la modificación del perfil, no se incluye en esta tarea

**Comment by maribelrb22** [comment]
FRQ-11 incluirlo en el S2 al ser un requisito para poder realizar el registro de un nuevo usuario. 
Igualmente está realizado el formulario de datos personales y de vehículo y únicamente faltaría realizar la comunicación con el backend para que el registro se lleve a cabo.
